"""initial schema: providers, sources, listings

Revision ID: 32cca32a3956
Revises: 
Create Date: 2026-06-01 17:12:49.434540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32cca32a3956'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_provider_id'), 'sources', ['provider_id'], unique=False)
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.Date(), nullable=True),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.String(length=100), nullable=True),
    sa.Column('race_approved', sa.Boolean(), nullable=True),
    sa.Column('race_program_number', sa.String(length=64), nullable=True),
    sa.Column('credit_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('presenter', sa.String(length=500), nullable=True),
    sa.Column('audience', sa.String(length=64), nullable=True),
    sa.Column('delivery_method', sa.String(length=100), nullable=True),
    sa.Column('subject_category', sa.String(length=100), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('registration_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_html_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_provider_id'), 'listings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_listings_raw_html_hash'), 'listings', ['raw_html_hash'], unique=False)
    op.create_index(op.f('ix_listings_source_id'), 'listings', ['source_id'], unique=False)
    op.create_index(op.f('ix_listings_source_url'), 'listings', ['source_url'], unique=True)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_url'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_raw_html_hash'), table_name='listings')
    op.drop_index(op.f('ix_listings_provider_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_index(op.f('ix_sources_provider_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
