"""add duplicate_of FK to listings

Revision ID: 4edd9e17054b
Revises: 8a45f171d7b9
Create Date: 2026-06-08 10:01:31.112797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edd9e17054b'
down_revision: Union[str, Sequence[str], None] = '8a45f171d7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('duplicate_of', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_listings_duplicate_of'), 'listings', ['duplicate_of'], unique=False)
    op.create_foreign_key(None, 'listings', 'listings', ['duplicate_of'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_index(op.f('ix_listings_duplicate_of'), table_name='listings')
    op.drop_column('listings', 'duplicate_of')
    # ### end Alembic commands ###
