"""add cron_expression to sources

Revision ID: 8a45f171d7b9
Revises: e35ea1978e96
Create Date: 2026-06-03 18:47:10.865603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a45f171d7b9'
down_revision: Union[str, Sequence[str], None] = 'e35ea1978e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('cron_expression', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'cron_expression')
    # ### end Alembic commands ###
