"""add subject_tagged_at and index subject_category

Revision ID: ad36d7b28761
Revises: ea2564ac1273
Create Date: 2026-06-16 21:30:39.612480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad36d7b28761'
down_revision: Union[str, Sequence[str], None] = 'ea2564ac1273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('subject_tagged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_listings_subject_category'), 'listings', ['subject_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_subject_category'), table_name='listings')
    op.drop_column('listings', 'subject_tagged_at')
    # ### end Alembic commands ###
